### ISSUE TITLE
Ability to send full strings

### ISSUE THREAD

**Issue by gullradriel** [portapack-mayhem/MayhemHub#14]
We would like the ability to send full strings, and if the focus is on a text edit entry set that text edit to string.

That, or a full ASCII keyboard mapping linked with the textedit buttons .

Edit: implementation in portapack side, see PR https://github.com/eried/portapack-mayhem/pull/1708

**Comment by htotoo** [comment]
This could be a base for that: https://github.com/eried/portapack-mayhem/pull/1708

**Comment by jLynx** [comment]
This should now be implemented as of https://github.com/portapack-mayhem/MayhemHub/pull/19. Please let me know if I have missed anything
