### ISSUE TITLE
ability to grab the screen

### ISSUE THREAD

**Issue by gullradriel** [portapack-mayhem/MayhemHub#4]
We would like to implement the Screen Sharing functions that can be seen in that app:

https://github.com/htotoo/PPRemoteSharp

But on the web app.

Ability to take screenshot of only the PP screen only would be awesome.

**Comment by jLynx** [comment]
Currently wip here https://github.com/portapack-mayhem/MayhemHub/tree/screenshot

**Comment by jLynx** [comment]
Added here https://github.com/portapack-mayhem/MayhemHub/pull/9****
