### ISSUE TITLE
support for single app+bin tar flash

### ISSUE THREAD

**Issue by gullradriel** [portapack-mayhem/MayhemHub#5]
We would like to add support for the incoming single tar of APPS and firmware bin.

See that PR for implementation:

https://github.com/eried/portapack-mayhem/pull/1704

Ideally, the web app could retrieve the file directly on github nightly or stable releases, and also allow tar file provide from host for manual selection and flash (devs ?)

**Comment by jLynx** [comment]
Have now added support for this
