### ISSUE TITLE
Allow the users to hide/reduce parts of the GUI

### ISSUE THREAD

**Issue by gullradriel** [portapack-mayhem/MayhemHub#55]
Sometime I prefer to just use my keyboard and pilot my Portapack that way. 
For it to be quick and effective, I'm not using the live view for this.
Sometimes I prefer to do commands, and I don't care the keyboard or live view or whatever.

It would be great if we could hide/reduce each items of the GUI, separately (I mean one hide button per item)

That would allow one to make a custom view more adjusted to the usage.

**Comment by pedroCX486** [comment]
I’m taking this challenge 🫡
