### ISSUE TITLE
hackrf.app firmware update on MacOS does not work

### ISSUE THREAD

**Issue by pgiacalo** [portapack-mayhem/MayhemHub#69]
The Firmware update at the hackrf.app website does not work when using a Macbook. I have v2.0.0 installed on the portapack. I am able to successfully connect to the portapack but when I click the "Update to latest stable release" button nothing appears to happen. 

I am running macOS 12.7.3 on a MacBook Pro (16-inch, 2019).

**Comment by htotoo** [comment]
Duplicate of #43 , please track the issue there.
