### ISSUE TITLE
Detection Jammer

### ISSUE THREAD

**Issue by fkarlitepe** [portapack-mayhem/MayhemHub#77]
Jamming up to 60 db can be produced thanks to the jammer application. I tested it and it works. How to detect the amount of jam with another HackRf device?

**Comment by HeBryG** [comment]
@fkarlitepe This question doesn't belong in this repository. Neither is an issue. The hackRF can detect the jamming as any other sdr would, monitoring the target frequencies of the jamming and seeing the signals sent on the spectrum. For more information ask in the discord channel: https://discord.gg/JdXEYc7X
